version: '2'
services:
  graphite:
    image: quay.io/alayacare/owl.graphite
    container_name: graphite-server
    restart: always
    ports:
      - "2003:2003"
    volumes:
      - /data/graphite/storage/whisper:/opt/graphite/storage/whisper
    labels:
      io.rancher.container.pull_image: always
  graphite-beacon:
    image: quay.io/alayacare/owl.graphite-beacon
    container_name: graphite-server-beacon
    labels:
      io.rancher.container.pull_image: always
    depends_on:
      - graphite
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    labels:
      io.rancher.container.pull_image: always
    depends_on:
      - graphite-beacon
    ports:
      - "3000:3000"
    links:
      - graphite:graphite-server
    environment:
      - GF_SECURITY_ADMIN_USER=alayadash
      - GF_SECURITY_ADMIN_PASSWORD=hpjxnbqbxEABDKiQ63ksyYp6N356Tms1xFELjokw
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
  grafana-auto:
    image: quay.io/alayacare/owl.grafana-auto
    container_name: grafana-auto
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
    links:
      - grafana
    depends_on:
      - grafana
    environment:
      - GF_USER=alayadash
      - GF_PASSWORD=hpjxnbqbxEABDKiQ63ksyYp6N356Tms1xFELjokw
  maildev:
    image: djfarrelly/maildev
    container_name: maildev-server
    labels:
      io.rancher.container.pull_image: always
    depends_on:
      - grafana-auto
    ports:
      - "1025:25"

